// with-vue/src/App.vue
<script>
import { defineComponent } from "vue";
import impact from "@mateonunez/lyra-impact";
import { search } from "@lyrasearch/lyra";

export default defineComponent({
  name: "App",

  data: () => ({
    lyra: null,
    isLoading: true,
    searchPokemon: [],
    search: "",
  }),

  created() {},

  mounted() {
    impact(
      "https://raw.githubusercontent.com/nearform/lyra/main/packages/examples/with-react/public/pokedex.json",
      {
        property: "pokemon",
      }
    )
      .then((lyra) => {
        this.lyra = lyra;
      })
      .catch(console.error)
      .finally(() => {
        this.isLoading = false;
      });
  },

  watch: {
    search(newValue) {
      if (newValue) {
        const { hits } = search(this.lyra, {
          term: newValue,
          properties: ["name"],
        });

        if (hits.length && !hits.some((x) => !x)) {
          this.searchPokemon = [...new Set(hits)];
        } else {
          this.searchPokemon = [];
        }
      }
    },
  },
});
</script>

<template>
  <main>
    <div class="flex w-full justify-center font-sans">
      <div class="ma">
        <h1>Lyra Impact with Vue</h1>

        <div className="w-full h-8">
          <input
            className="w-full h-full border-rounded border-1 border-gray-500 pl-2"
            type="text"
            v-model="search"
            placeholder="Find a Pokemon..."
          />
        </div>

        <div v-if="!isLoading">
          <div class="grid mt-4">
            <!-- Render Pokemon grid -->
            <div
              v-for="p in searchPokemon"
              :key="p.id"
              class="grid grid-cols-2 my-2"
            >
              <img :src="p.img" />

              <div>
                <h2 class="text-lg">{{ p.name }}</h2>
                <p>Type: {{ p.type.join(", ") }}</p>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </main>
</template>

// with-react/src/App.jsx
import { useEffect, useState } from "react";
import impact from "@mateonunez/lyra-impact";
import { search as lyraSearch } from "@lyrasearch/lyra";

function App() {
  const [lyra, setLyra] = useState(null);
  const [isLoading, setIsLoading] = useState(true);
  const [searchPokemon, setSearchPokemon] = useState([]);
  const [search, setSearch] = useState("");

  useEffect(() => {
    impact(
      "https://raw.githubusercontent.com/nearform/lyra/main/packages/examples/with-react/public/pokedex.json",
      {
        property: "pokemon",
      }
    )
      .then(setLyra)
      .catch(console.error)
      .finally(() => setIsLoading(false));
  }, []);

  useEffect(() => {
    if (search) {
      const { hits } = lyraSearch(lyra, {
        term: search,
        properties: ["name"],
      });

      if (hits.length && !hits.some((x) => !x)) {
        setSearchPokemon([...new Set(hits)]);
      } else {
        setSearchPokemon([]);
      }
    }
  }, [search]);

  return (
    <main>
      <div className="flex w-full justify-center font-sans">
        <div className="ma">
          <h1>Lyra Impact with React</h1>

          <div className="w-full h-8">
            <input
              className="w-full h-full border-rounded border-1 border-gray-500 pl-2"
              type="text"
              placeholder="Find a Pokemon..."
              onChange={(e) => setSearch(e.target.value)}
            />
          </div>

          {!isLoading && (
            <div className="grid mt-4">
              {searchPokemon.map((pokemon) => (
                <div className="grid grid-cols-2 my-2" key={pokemon.name}>
                  <img src={pokemon.img} />

                  <div>
                    <h2>{pokemon.name}</h2>
                    <p>{pokemon.type.join(", ")}</p>
                  </div>
                </div>
              ))}
            </div>
          )}
        </div>
      </div>
    </main>
  );
}

export default App;
